// AUTO-GENERATED by scripts/generate-types.mjs — do not edit by hand.
// Regenerate with `npm run pb:types` after every PocketBase schema change.

/** A 15-character PocketBase record id, tagged with the collection it points at. */
export type RecordId<C extends CollectionName = CollectionName> = string & {
  readonly __collection?: C;
};

/** Fields PocketBase maintains on every record in this schema. */
export interface BaseRecord {
  id: string;
  created: string;
  updated: string;
  collectionId: string;
  collectionName: string;
  expand?: Record<string, unknown>;
}

/** `comments` */
export interface CommentsRecord extends BaseRecord {
  body: string;
  author: RecordId<'users'>;
  procedure?: RecordId<'procedures'>;
  procedure_item?: RecordId<'procedure_items'>;
  directorate?: RecordId<'directorates'>;
  ministry?: RecordId<'ministries'>;
  approved?: boolean;
}

/** `contact` */
export interface ContactRecord extends BaseRecord {
  first_name: string;
  last_name: string;
  email: string;
  phone?: string;
  message: string;
  status?: 'new' | 'in_progress' | 'resolved' | 'spam';
  handled_by?: RecordId<'users'>;
}

/** `directorate_branches` */
export interface DirectorateBranchesRecord extends BaseRecord {
  title_en: string;
  title_ar: string;
  title_ku?: string;
  directorate: RecordId<'directorates'>;
  province: RecordId<'provinces'>;
  address_en?: string;
  address_ar?: string;
  address_ku?: string;
  gps_lat?: number;
  gps_lon?: number;
  phone?: string;
  sort_order?: number;
  archived?: boolean;
  photos?: string[];
}

/** `directorates` */
export interface DirectoratesRecord extends BaseRecord {
  slug: string;
  title_en: string;
  title_ar: string;
  title_ku?: string;
  ministry: RecordId<'ministries'>;
  logo?: string;
  address_en?: string;
  address_ar?: string;
  address_ku?: string;
  gps_lat?: number;
  gps_lon?: number;
  website?: string;
  phone?: string;
  email?: string;
  sort_order?: number;
  archived?: boolean;
  photos?: string[];
  working_hours?: unknown;
}

/** `faq` */
export interface FaqRecord extends BaseRecord {
  question_en: string;
  question_ar: string;
  question_ku?: string;
  answer_en?: string;
  answer_ar?: string;
  answer_ku?: string;
  sort_order?: number;
  enabled?: boolean;
  procedure?: RecordId<'procedures'>;
}

/** `files` */
export interface FilesRecord extends BaseRecord {
  title_en: string;
  title_ar: string;
  title_ku?: string;
  document?: string;
  external_url?: string;
  procedure?: RecordId<'procedures'>;
  procedure_item?: RecordId<'procedure_items'>;
  sort_order?: number;
}

/** `ministries` */
export interface MinistriesRecord extends BaseRecord {
  slug: string;
  title_en: string;
  title_ar: string;
  title_ku?: string;
  logo?: string;
  krg?: boolean;
  address_en?: string;
  address_ar?: string;
  address_ku?: string;
  gps_lat?: number;
  gps_lon?: number;
  website?: string;
  phone?: string;
  email?: string;
  sort_order?: number;
  archived?: boolean;
}

/** `navigation` */
export interface NavigationRecord extends BaseRecord {
  title_en: string;
  title_ar: string;
  title_ku?: string;
  endpoint?: string;
  placement: 'menu' | 'drawer';
  parent?: RecordId<'navigation'>;
  icon?: string;
  sort_order?: number;
  enabled?: boolean;
}

/** `partners` */
export interface PartnersRecord extends BaseRecord {
  name_en: string;
  name_ar: string;
  name_ku?: string;
  logo?: string;
  link?: string;
  location?: 'home' | 'footer' | 'partners_page';
  sort_order?: number;
  enabled?: boolean;
}

/** `procedure_items` */
export interface ProcedureItemsRecord extends BaseRecord {
  procedure: RecordId<'procedures'>;
  title_en: string;
  title_ar: string;
  title_ku?: string;
  description_en?: string;
  description_ar?: string;
  description_ku?: string;
  url?: string;
  sort_order?: number;
  enabled?: boolean;
}

/** `procedure_submissions` */
export interface ProcedureSubmissionsRecord extends BaseRecord {
  user: RecordId<'users'>;
  title: string;
  summary?: string;
  ministry?: RecordId<'ministries'>;
  directorate?: RecordId<'directorates'>;
  steps?: unknown;
  documents?: unknown;
  fee_iqd?: number;
  processing_time?: string;
  notes?: string;
  status: 'submitted' | 'in_review' | 'approved' | 'rejected';
  review_note?: string;
}

/** `procedures` */
export interface ProceduresRecord extends BaseRecord {
  slug: string;
  title_en: string;
  title_ar: string;
  title_ku?: string;
  summary_en?: string;
  summary_ar?: string;
  summary_ku?: string;
  description_en?: string;
  description_ar?: string;
  description_ku?: string;
  directorate: RecordId<'directorates'>;
  tags?: RecordId<'tags'>[];
  fee_iqd?: number;
  processing_time_en?: string;
  processing_time_ar?: string;
  processing_time_ku?: string;
  enabled?: boolean;
  featured?: boolean;
  publish_date?: string;
  sort_order?: number;
  archived?: boolean;
}

/** `provinces` */
export interface ProvincesRecord extends BaseRecord {
  code: string;
  name_en: string;
  name_ar: string;
  name_ku: string;
  krg?: boolean;
  gps_lat?: number;
  gps_lon?: number;
  sort_order?: number;
}

/** `reviews` */
export interface ReviewsRecord extends BaseRecord {
  rating: number;
  body?: string;
  author: RecordId<'users'>;
  procedure?: RecordId<'procedures'>;
  procedure_item?: RecordId<'procedure_items'>;
  directorate?: RecordId<'directorates'>;
  ministry?: RecordId<'ministries'>;
  approved?: boolean;
}

/** `settings` */
export interface SettingsRecord extends BaseRecord {
  key: string;
  title: string;
  group?: 'general' | 'contact' | 'social' | 'seo';
  no_trans?: boolean;
  value_en?: string;
  value_ar?: string;
  value_ku?: string;
}

/** `slider` */
export interface SliderRecord extends BaseRecord {
  title_en: string;
  title_ar: string;
  title_ku?: string;
  subtitle_en?: string;
  subtitle_ar?: string;
  subtitle_ku?: string;
  image?: string;
  link?: string;
  sort_order?: number;
  enabled?: boolean;
}

/** `tags` */
export interface TagsRecord extends BaseRecord {
  slug: string;
  name_en: string;
  name_ar: string;
  name_ku?: string;
}

/** `team` */
export interface TeamRecord extends BaseRecord {
  name_en: string;
  name_ar: string;
  name_ku?: string;
  job_title_en?: string;
  job_title_ar?: string;
  job_title_ku?: string;
  bio_en?: string;
  bio_ar?: string;
  bio_ku?: string;
  photo?: string;
  email?: string;
  location?: 'leadership' | 'staff' | 'advisory';
  sort_order?: number;
  enabled?: boolean;
}

/** `users` (auth collection) */
export interface UsersRecord extends BaseRecord {
  email: string;
  emailVisibility: boolean;
  verified: boolean;
  full_name: string;
  job_title?: string;
  role: 'user' | 'moderator' | 'admin';
  avatar?: string;
}

/** Every collection in the schema, keyed by name. */
export interface CollectionRecords {
  comments: CommentsRecord;
  contact: ContactRecord;
  directorate_branches: DirectorateBranchesRecord;
  directorates: DirectoratesRecord;
  faq: FaqRecord;
  files: FilesRecord;
  ministries: MinistriesRecord;
  navigation: NavigationRecord;
  partners: PartnersRecord;
  procedure_items: ProcedureItemsRecord;
  procedure_submissions: ProcedureSubmissionsRecord;
  procedures: ProceduresRecord;
  provinces: ProvincesRecord;
  reviews: ReviewsRecord;
  settings: SettingsRecord;
  slider: SliderRecord;
  tags: TagsRecord;
  team: TeamRecord;
  users: UsersRecord;
}

export type CollectionName = keyof CollectionRecords;

export const COLLECTION_NAMES = [
  'comments',
  'contact',
  'directorate_branches',
  'directorates',
  'faq',
  'files',
  'ministries',
  'navigation',
  'partners',
  'procedure_items',
  'procedure_submissions',
  'procedures',
  'provinces',
  'reviews',
  'settings',
  'slider',
  'tags',
  'team',
  'users',
] as const satisfies readonly CollectionName[];

/** Role values on the `users` collection. */
export type UserRole = 'user' | 'moderator' | 'admin';

export const STAFF_ROLES = ['moderator', 'admin'] as const satisfies readonly UserRole[];

/** Locale suffixes used by translatable content fields. */
export type ContentLocale = 'en' | 'ar' | 'ku';
