// Generates src/types/pb.ts from the PocketBase schema.
//
//   node scripts/generate-types.mjs            # from pocketbase/schema.json
//   node scripts/generate-types.mjs --live     # from the live instance (needs PB_URL/PB_EMAIL/PB_PASSWORD)
//
// Never hand-edit the output — regenerate after every schema change.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = resolve(ROOT, 'src/types/pb.ts');
const SNAPSHOT = resolve(ROOT, 'pocketbase/schema.json');

const SYSTEM_FIELDS = new Set(['id', 'created', 'updated']);
const HIDDEN_TYPES = new Set(['password', 'autodate']);

async function loadLive() {
  const { PB_URL, PB_EMAIL, PB_PASSWORD } = process.env;
  if (!PB_URL || !PB_EMAIL || !PB_PASSWORD) {
    console.error('--live needs PB_URL, PB_EMAIL and PB_PASSWORD');
    process.exit(1);
  }
  const auth = await fetch(`${PB_URL}/api/collections/_superusers/auth-with-password`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ identity: PB_EMAIL, password: PB_PASSWORD }),
  }).then((r) => r.json());
  const res = await fetch(`${PB_URL}/api/collections?perPage=200`, {
    headers: { Authorization: auth.token },
  }).then((r) => r.json());
  return res.items.filter((c) => !c.system || c.id === '_pb_users_auth_');
}

const pascal = (s) => s.split(/[_-]/).map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join('');
const quote = (s) => `'${s.replace(/'/g, "\\'")}'`;

function tsType(field, collectionsById) {
  const many = (t) => (field.maxSelect && field.maxSelect > 1 ? `${t}[]` : t);
  switch (field.type) {
    case 'number':
      return 'number';
    case 'bool':
      return 'boolean';
    case 'select': {
      const union = (field.values ?? []).map(quote).join(' | ') || 'string';
      return field.maxSelect && field.maxSelect > 1 ? `Array<${union}>` : union;
    }
    case 'relation': {
      const target = collectionsById.get(field.collectionId);
      const doc = target ? `RecordId<${quote(target.name)}>` : 'string';
      return many(doc);
    }
    case 'file':
      return many('string');
    case 'json':
      return 'unknown';
    default:
      // text, editor, email, url, date, autodate, geoPoint fallback
      return 'string';
  }
}

function build(collections) {
  const byId = new Map(collections.map((c) => [c.id, c]));
  const ordered = [...collections].sort((a, b) => a.name.localeCompare(b.name));

  const out = [];
  out.push('// AUTO-GENERATED by scripts/generate-types.mjs — do not edit by hand.');
  out.push('// Regenerate with `npm run pb:types` after every PocketBase schema change.');
  out.push('');
  out.push('/** A 15-character PocketBase record id, tagged with the collection it points at. */');
  out.push('export type RecordId<C extends CollectionName = CollectionName> = string & {');
  out.push('  readonly __collection?: C;');
  out.push('};');
  out.push('');
  out.push('/** Fields PocketBase maintains on every record in this schema. */');
  out.push('export interface BaseRecord {');
  out.push('  id: string;');
  out.push('  created: string;');
  out.push('  updated: string;');
  out.push('  collectionId: string;');
  out.push('  collectionName: string;');
  out.push('  expand?: Record<string, unknown>;');
  out.push('}');
  out.push('');

  for (const c of ordered) {
    const iface = `${pascal(c.name)}Record`;
    const fields = c.fields.filter(
      (f) => !SYSTEM_FIELDS.has(f.name) && !HIDDEN_TYPES.has(f.type) && !f.hidden,
    );
    out.push(`/** \`${c.name}\`${c.type === 'auth' ? ' (auth collection)' : ''} */`);
    out.push(`export interface ${iface} extends BaseRecord {`);
    if (c.type === 'auth') {
      out.push('  email: string;');
      out.push('  emailVisibility: boolean;');
      out.push('  verified: boolean;');
    }
    for (const f of fields) {
      if (c.type === 'auth' && ['email', 'emailVisibility', 'verified'].includes(f.name)) continue;
      const optional = f.required ? '' : '?';
      out.push(`  ${f.name}${optional}: ${tsType(f, byId)};`);
    }
    out.push('}');
    out.push('');
  }

  out.push('/** Every collection in the schema, keyed by name. */');
  out.push('export interface CollectionRecords {');
  for (const c of ordered) out.push(`  ${c.name}: ${pascal(c.name)}Record;`);
  out.push('}');
  out.push('');
  out.push('export type CollectionName = keyof CollectionRecords;');
  out.push('');
  out.push('export const COLLECTION_NAMES = [');
  for (const c of ordered) out.push(`  ${quote(c.name)},`);
  out.push('] as const satisfies readonly CollectionName[];');
  out.push('');

  // Convenience unions used across the admin UI.
  const users = collections.find((c) => c.name === 'users');
  const role = users?.fields.find((f) => f.name === 'role');
  if (role?.values?.length) {
    out.push('/** Role values on the `users` collection. */');
    out.push(`export type UserRole = ${role.values.map(quote).join(' | ')};`);
    out.push('');
    out.push(`export const STAFF_ROLES = ['moderator', 'admin'] as const satisfies readonly UserRole[];`);
    out.push('');
  }

  out.push('/** Locale suffixes used by translatable content fields. */');
  out.push("export type ContentLocale = 'en' | 'ar' | 'ku';");
  out.push('');
  return out.join('\n');
}

const collections = process.argv.includes('--live')
  ? await loadLive()
  : JSON.parse(readFileSync(SNAPSHOT, 'utf8'));

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, build(collections), 'utf8');
console.log(`Wrote ${OUT} — ${collections.length} collections`);
