// Reference data: provinces, ministries, directorates, branches, tags.
// IDs are fixed 15-char PocketBase ids so the seed is idempotent and relations are readable.
export const pid = (prefix, n) => prefix + String(n).padStart(12, '0');

const HOURS = {
  working_hours_en: 'Sunday – Thursday, 08:00 – 14:00. Closed Friday and Saturday.',
  working_hours_ar: 'الأحد – الخميس، ٨:٠٠ – ١٤:٠٠. عطلة الجمعة والسبت.',
  working_hours_ku: 'یەکشەممە – پێنجشەممە، ٨:٠٠ – ١٤:٠٠. هەینی و شەممە داخراوە.',
};

export const provinces = [
  ['IQ-BG', 'Baghdad', 'بغداد', 'بەغدا', false, 33.3152, 44.3661],
  ['IQ-BA', 'Basra', 'البصرة', 'بەسرە', false, 30.5085, 47.7804],
  ['IQ-NI', 'Nineveh', 'نينوى', 'نەینەوا', false, 36.335, 43.1189],
  ['IQ-AR', 'Erbil', 'أربيل', 'هەولێر', true, 36.1901, 44.0091],
  ['IQ-SU', 'Sulaymaniyah', 'السليمانية', 'سلێمانی', true, 35.5556, 45.4351],
  ['IQ-DA', 'Duhok', 'دهوك', 'دهۆک', true, 36.8669, 42.9503],
  ['IQ-HA', 'Halabja', 'حلبجة', 'هەڵەبجە', true, 35.1778, 45.9864],
  ['IQ-KI', 'Kirkuk', 'كركوك', 'کەرکووک', false, 35.4681, 44.3922],
  ['IQ-AN', 'Al-Anbar', 'الأنبار', 'ئەنبار', false, 33.4258, 43.3006],
  ['IQ-BB', 'Babil', 'بابل', 'بابل', false, 32.4637, 44.4211],
  ['IQ-KA', 'Karbala', 'كربلاء', 'کەربەلا', false, 32.616, 44.0249],
  ['IQ-NA', 'Najaf', 'النجف', 'نەجەف', false, 31.989, 44.3148],
  ['IQ-DI', 'Diyala', 'ديالى', 'دیالە', false, 33.7736, 45.1436],
  ['IQ-DQ', 'Dhi Qar', 'ذي قار', 'زیقار', false, 31.0526, 46.257],
  ['IQ-MA', 'Maysan', 'ميسان', 'مەیسان', false, 31.8356, 47.145],
  ['IQ-MU', 'Al-Muthanna', 'المثنى', 'موسەننا', false, 31.332, 45.279],
  ['IQ-QA', 'Al-Qadisiyyah', 'القادسية', 'قادسیە', false, 31.989, 44.925],
  ['IQ-WA', 'Wasit', 'واسط', 'واسیت', false, 32.5152, 45.8181],
  ['IQ-SD', 'Salah al-Din', 'صلاح الدين', 'سەلاحەدین', false, 34.6, 43.6833],
].map(([code, en, ar, ku, krg, lat, lon], i) => ({
  id: pid('prv', i + 1),
  code, name_en: en, name_ar: ar, name_ku: ku,
  krg, gps_lat: lat, gps_lon: lon, sort_order: i + 1,
}));

export const ministries = [
  ['ministry-of-interior', 'Ministry of Interior', 'وزارة الداخلية', 'وەزارەتی ناوخۆ', false,
    'Al-Andalus Square, Karrada, Baghdad', 'ساحة الأندلس، الكرادة، بغداد', 'گۆڕەپانی ئەندەلوس، کەڕادە، بەغدا',
    33.3061, 44.4092, 'https://moi.gov.iq', '+964 780 000 1000', 'info@moi.gov.iq'],
  ['ministry-of-health', 'Ministry of Health', 'وزارة الصحة', 'وەزارەتی تەندروستی', false,
    'Bab Al-Muadham, Baghdad', 'باب المعظم، بغداد', 'بابولموعەزەم، بەغدا',
    33.3486, 44.3872, 'https://moh.gov.iq', '+964 780 000 2000', 'info@moh.gov.iq'],
  ['ministry-of-education', 'Ministry of Education', 'وزارة التربية', 'وەزارەتی پەروەردە', false,
    'Al-Mansour, Baghdad', 'المنصور، بغداد', 'مەنسوور، بەغدا',
    33.3128, 44.3245, 'https://moedu.gov.iq', '+964 780 000 3000', 'info@moedu.gov.iq'],
  ['ministry-of-higher-education', 'Ministry of Higher Education and Scientific Research',
    'وزارة التعليم العالي والبحث العلمي', 'وەزارەتی خوێندنی باڵا و توێژینەوەی زانستی', false,
    'Al-Jadiriyah, Baghdad', 'الجادرية، بغداد', 'جادریە، بەغدا',
    33.2745, 44.3801, 'https://mohesr.gov.iq', '+964 780 000 4000', 'info@mohesr.gov.iq'],
  ['ministry-of-finance', 'Ministry of Finance', 'وزارة المالية', 'وەزارەتی دارایی', false,
    'Al-Karkh, Baghdad', 'الكرخ، بغداد', 'کەرخ، بەغدا',
    33.3055, 44.3661, 'https://mof.gov.iq', '+964 780 000 5000', 'info@mof.gov.iq'],
  ['ministry-of-justice', 'Ministry of Justice', 'وزارة العدل', 'وەزارەتی دادپەروەری', false,
    'Al-Salhiya, Baghdad', 'الصالحية، بغداد', 'ساڵحیە، بەغدا',
    33.3211, 44.3789, 'https://moj.gov.iq', '+964 780 000 6000', 'info@moj.gov.iq'],
  ['ministry-of-labour-and-social-affairs', 'Ministry of Labour and Social Affairs',
    'وزارة العمل والشؤون الاجتماعية', 'وەزارەتی کار و کاروباری کۆمەڵایەتی', false,
    'Al-Waziriya, Baghdad', 'الوزيرية، بغداد', 'وەزیریە، بەغدا',
    33.3606, 44.4042, 'https://molsa.gov.iq', '+964 780 000 7000', 'info@molsa.gov.iq'],
  ['ministry-of-trade', 'Ministry of Trade', 'وزارة التجارة', 'وەزارەتی بازرگانی', false,
    'Al-Nidhal Street, Baghdad', 'شارع النضال، بغداد', 'شەقامی نیزاڵ، بەغدا',
    33.3138, 44.4204, 'https://mot.gov.iq', '+964 780 000 8000', 'info@mot.gov.iq'],
  ['ministry-of-transport', 'Ministry of Transport', 'وزارة النقل', 'وەزارەتی گواستنەوە', false,
    'Al-Nahda, Baghdad', 'النهضة، بغداد', 'نەهزە، بەغدا',
    33.3, 44.4167, 'https://motrans.gov.iq', '+964 780 000 9000', 'info@motrans.gov.iq'],
  ['ministry-of-planning', 'Ministry of Planning', 'وزارة التخطيط', 'وەزارەتی پلاندانان', false,
    'Al-Karkh, Baghdad', 'الكرخ، بغداد', 'کەرخ، بەغدا',
    33.3092, 44.3593, 'https://mop.gov.iq', '+964 780 001 0000', 'info@mop.gov.iq'],
  ['krg-ministry-of-interior', 'Ministry of Interior — Kurdistan Region',
    'وزارة الداخلية — إقليم كردستان', 'وەزارەتی ناوخۆ — هەرێمی کوردستان', true,
    'Council of Ministers Compound, Erbil', 'مجمع مجلس الوزراء، أربيل', 'کۆمەڵگای ئەنجومەنی وەزیران، هەولێر',
    36.1911, 44.0092, 'https://gov.krd', '+964 750 000 1000', 'info@moi.gov.krd'],
  ['krg-ministry-of-health', 'Ministry of Health — Kurdistan Region',
    'وزارة الصحة — إقليم كردستان', 'وەزارەتی تەندروستی — هەرێمی کوردستان', true,
    '40m Street, Erbil', 'شارع الأربعين، أربيل', 'شەقامی چل مەتری، هەولێر',
    36.2043, 44.0089, 'https://gov.krd', '+964 750 000 2000', 'info@moh.gov.krd'],
  ['krg-ministry-of-higher-education', 'Ministry of Higher Education and Scientific Research — Kurdistan Region',
    'وزارة التعليم العالي والبحث العلمي — إقليم كردستان', 'وەزارەتی خوێندنی باڵا و توێژینەوەی زانستی — هەرێمی کوردستان', true,
    'Erbil–Shaqlawa Road, Erbil', 'طريق أربيل - شقلاوة، أربيل', 'ڕێگای هەولێر ـ شەقڵاوە، هەولێر',
    36.2211, 44.0378, 'https://mhe.krd', '+964 750 000 3000', 'info@mhe.krd'],
  ['krg-ministry-of-municipalities-and-tourism', 'Ministry of Municipalities and Tourism — Kurdistan Region',
    'وزارة البلديات والسياحة — إقليم كردستان', 'وەزارەتی شارەوانی و گەشتوگوزار — هەرێمی کوردستان', true,
    'Erbil Citadel Road, Erbil', 'طريق قلعة أربيل، أربيل', 'ڕێگای قەڵای هەولێر، هەولێر',
    36.1912, 44.0093, 'https://gov.krd', '+964 750 000 4000', 'info@momt.gov.krd'],
].map(([slug, en, ar, ku, krg, aEn, aAr, aKu, lat, lon, web, phone, email], i) => ({
  id: pid('min', i + 1),
  slug, title_en: en, title_ar: ar, title_ku: ku, krg,
  address_en: aEn, address_ar: aAr, address_ku: aKu,
  gps_lat: lat, gps_lon: lon, website: web, phone, email,
  sort_order: i + 1, archived: false,
}));

// [slug, en, ar, ku, ministryIndex, addr_en, addr_ar, addr_ku, lat, lon, phone]
export const directorates = [
  ['general-directorate-of-nationality', 'General Directorate of Nationality', 'المديرية العامة للجنسية', 'بەڕێوەبەرایەتی گشتی ڕەگەزنامە', 1,
    'Al-Nisour Square, Baghdad', 'ساحة النسور، بغداد', 'گۆڕەپانی نیسوور، بەغدا', 33.3128, 44.3542, '+964 780 100 1001'],
  ['general-directorate-of-passports', 'General Directorate of Passports', 'مديرية شؤون الجوازات العامة', 'بەڕێوەبەرایەتی گشتی پاسپۆرت', 1,
    'Al-Karkh Passport Complex, Baghdad', 'مجمع جوازات الكرخ، بغداد', 'کۆمەڵگای پاسپۆرتی کەرخ، بەغدا', 33.3018, 44.3401, '+964 780 100 1002'],
  ['general-directorate-of-traffic', 'General Directorate of Traffic', 'مديرية المرور العامة', 'بەڕێوەبەرایەتی گشتی هاتوچۆ', 1,
    'Al-Rusafa Traffic Complex, Baghdad', 'مجمع مرور الرصافة، بغداد', 'کۆمەڵگای هاتوچۆی ڕوسافە، بەغدا', 33.3402, 44.4212, '+964 780 100 1003'],
  ['general-directorate-of-residence', 'General Directorate of Residence', 'مديرية الإقامة العامة', 'بەڕێوەبەرایەتی گشتی نیشتەجێبوون', 1,
    'Al-Mansour, Baghdad', 'المنصور، بغداد', 'مەنسوور، بەغدا', 33.3151, 44.3298, '+964 780 100 1004'],
  ['directorate-of-public-health', 'Directorate of Public Health', 'دائرة الصحة العامة', 'بەڕێوەبەرایەتی تەندروستی گشتی', 2,
    'Bab Al-Muadham, Baghdad', 'باب المعظم، بغداد', 'بابولموعەزەم، بەغدا', 33.3489, 44.3866, '+964 780 100 2001'],
  ['general-directorate-of-education-baghdad-rusafa', 'General Directorate of Education — Baghdad / Al-Rusafa', 'المديرية العامة لتربية بغداد الرصافة', 'بەڕێوەبەرایەتی گشتی پەروەردەی بەغدا ـ ڕوسافە', 3,
    'Palestine Street, Baghdad', 'شارع فلسطين، بغداد', 'شەقامی فەلەستین، بەغدا', 33.3475, 44.4318, '+964 780 100 3001'],
  ['directorate-of-studies-and-planning', 'Directorate of Studies, Planning and Follow-up', 'دائرة الدراسات والتخطيط والمتابعة', 'بەڕێوەبەرایەتی لێکۆڵینەوە و پلاندانان و بەدواداچوون', 4,
    'Al-Jadiriyah, Baghdad', 'الجادرية، بغداد', 'جادریە، بەغدا', 33.2751, 44.3812, '+964 780 100 4001'],
  ['directorate-of-missions-and-cultural-relations', 'Directorate of Missions and Cultural Relations', 'دائرة البعثات والعلاقات الثقافية', 'بەڕێوەبەرایەتی نێردراوان و پەیوەندییە ڕۆشنبیرییەکان', 4,
    'Al-Jadiriyah, Baghdad', 'الجادرية، بغداد', 'جادریە، بەغدا', 33.2748, 44.3808, '+964 780 100 4002'],
  ['general-commission-for-taxes', 'General Commission for Taxes', 'الهيئة العامة للضرائب', 'دەستەی گشتی باج', 5,
    'Al-Bab Al-Sharqi, Baghdad', 'الباب الشرقي، بغداد', 'دەروازەی ڕۆژهەڵات، بەغدا', 33.3199, 44.4056, '+964 780 100 5001'],
  ['general-commission-of-customs', 'General Commission of Customs', 'الهيئة العامة للكمارك', 'دەستەی گشتی گومرگ', 5,
    'Al-Karkh, Baghdad', 'الكرخ، بغداد', 'کەرخ، بەغدا', 33.3041, 44.3612, '+964 780 100 5002'],
  ['national-board-of-pensions', 'National Board of Pensions', 'هيئة التقاعد الوطنية', 'دەستەی نیشتمانی خانەنشینی', 5,
    'Al-Alawi, Baghdad', 'العلاوي، بغداد', 'عەلاوی، بەغدا', 33.3105, 44.3778, '+964 780 100 5003'],
  ['real-estate-registration-department', 'Real Estate Registration Department', 'دائرة التسجيل العقاري', 'بەڕێوەبەرایەتی تۆمارکردنی خانووبەرە', 6,
    'Al-Salhiya, Baghdad', 'الصالحية، بغداد', 'ساڵحیە، بەغدا', 33.3218, 44.3795, '+964 780 100 6001'],
  ['notary-public-department', 'Notary Public Department', 'دائرة الكاتب العدل', 'بەڕێوەبەرایەتی نووسەری دادوەری', 6,
    'Al-Salhiya, Baghdad', 'الصالحية، بغداد', 'ساڵحیە، بەغدا', 33.3222, 44.3801, '+964 780 100 6002'],
  ['social-protection-authority', 'Social Protection Authority', 'هيئة الحماية الاجتماعية', 'دەستەی پاراستنی کۆمەڵایەتی', 7,
    'Al-Waziriya, Baghdad', 'الوزيرية، بغداد', 'وەزیریە، بەغدا', 33.3611, 44.4051, '+964 780 100 7001'],
  ['companies-registration-department', 'Companies Registration Department', 'دائرة تسجيل الشركات', 'بەڕێوەبەرایەتی تۆمارکردنی کۆمپانیاکان', 8,
    'Al-Nidhal Street, Baghdad', 'شارع النضال، بغداد', 'شەقامی نیزاڵ، بەغدا', 33.3142, 44.4211, '+964 780 100 8001'],
  ['general-company-for-foodstuff-trading', 'General Company for Foodstuff Trading', 'الشركة العامة لتجارة المواد الغذائية', 'کۆمپانیای گشتی بازرگانی کەلوپەلی خۆراک', 8,
    'Al-Za\'franiya, Baghdad', 'الزعفرانية، بغداد', 'زەعفەرانیە، بەغدا', 33.2402, 44.4901, '+964 780 100 8002'],
  ['krg-general-directorate-of-nationality', 'General Directorate of Nationality — Kurdistan Region', 'المديرية العامة للجنسية — إقليم كردستان', 'بەڕێوەبەرایەتی گشتی ڕەگەزنامە — هەرێمی کوردستان', 11,
    '60m Street, Erbil', 'شارع الستين، أربيل', 'شەقامی شەست مەتری، هەولێر', 36.1998, 43.9922, '+964 750 100 1001'],
  ['krg-general-directorate-of-traffic', 'General Directorate of Traffic — Kurdistan Region', 'مديرية المرور العامة — إقليم كردستان', 'بەڕێوەبەرایەتی گشتی هاتوچۆ — هەرێمی کوردستان', 11,
    '100m Street, Erbil', 'شارع المائة، أربيل', 'شەقامی سەد مەتری، هەولێر', 36.2118, 44.0201, '+964 750 100 1002'],
].map(([slug, en, ar, ku, minIdx, aEn, aAr, aKu, lat, lon, phone], i) => ({
  id: pid('dir', i + 1),
  slug, title_en: en, title_ar: ar, title_ku: ku,
  ministry: pid('min', minIdx),
  address_en: aEn, address_ar: aAr, address_ku: aKu,
  gps_lat: lat, gps_lon: lon, ...HOURS,
  phone, sort_order: i + 1, archived: false,
}));

// [en, ar, ku, directorateIndex, provinceIndex, addr_en, addr_ar, addr_ku, lat, lon, phone]
export const branches = [
  ['Basra Passport Directorate', 'مديرية جوازات البصرة', 'بەڕێوەبەرایەتی پاسپۆرتی بەسرە', 2, 2,
    'Al-Ashar, Basra', 'العشار، البصرة', 'عەشار، بەسرە', 30.5257, 47.8134, '+964 780 200 0201'],
  ['Nineveh Passport Directorate', 'مديرية جوازات نينوى', 'بەڕێوەبەرایەتی پاسپۆرتی نەینەوا', 2, 3,
    'Al-Majmoua Al-Thaqafiya, Mosul', 'المجموعة الثقافية، الموصل', 'کۆمەڵەی ڕۆشنبیری، موسڵ', 36.3423, 43.1298, '+964 780 200 0301'],
  ['Erbil Passport Directorate', 'مديرية جوازات أربيل', 'بەڕێوەبەرایەتی پاسپۆرتی هەولێر', 2, 4,
    'Erbil–Kirkuk Road, Erbil', 'طريق أربيل - كركوك، أربيل', 'ڕێگای هەولێر ـ کەرکووک، هەولێر', 36.1662, 44.0341, '+964 750 200 0401'],
  ['Sulaymaniyah Passport Directorate', 'مديرية جوازات السليمانية', 'بەڕێوەبەرایەتی پاسپۆرتی سلێمانی', 2, 5,
    'Salim Street, Sulaymaniyah', 'شارع سالم، السليمانية', 'شەقامی سالم، سلێمانی', 35.5612, 45.4372, '+964 750 200 0501'],
  ['Basra Traffic Directorate', 'مديرية مرور البصرة', 'بەڕێوەبەرایەتی هاتوچۆی بەسرە', 3, 2,
    'Al-Jazair, Basra', 'الجزائر، البصرة', 'جەزائیر، بەسرە', 30.5164, 47.8021, '+964 780 200 0202'],
  ['Karbala Traffic Directorate', 'مديرية مرور كربلاء', 'بەڕێوەبەرایەتی هاتوچۆی کەربەلا', 3, 11,
    'Baghdad Road, Karbala', 'طريق بغداد، كربلاء', 'ڕێگای بەغدا، کەربەلا', 32.6284, 44.0451, '+964 780 200 1101'],
  ['Najaf Traffic Directorate', 'مديرية مرور النجف', 'بەڕێوەبەرایەتی هاتوچۆی نەجەف', 3, 12,
    'Al-Ameer District, Najaf', 'حي الأمير، النجف', 'گەڕەکی ئەمیر، نەجەف', 31.9971, 44.3241, '+964 780 200 1201'],
  ['Kirkuk Nationality Directorate', 'مديرية جنسية كركوك', 'بەڕێوەبەرایەتی ڕەگەزنامەی کەرکووک', 1, 8,
    'Al-Qadisiyah District, Kirkuk', 'حي القادسية، كركوك', 'گەڕەکی قادسیە، کەرکووک', 35.4712, 44.3841, '+964 780 200 0801'],
  ['Dhi Qar Nationality Directorate', 'مديرية جنسية ذي قار', 'بەڕێوەبەرایەتی ڕەگەزنامەی زیقار', 1, 14,
    'Al-Nasr District, Nasiriyah', 'حي النصر، الناصرية', 'گەڕەکی نەسر، ناسیریە', 31.0581, 46.2612, '+964 780 200 1401'],
  ['Duhok Nationality Directorate', 'مديرية جنسية دهوك', 'بەڕێوەبەرایەتی ڕەگەزنامەی دهۆک', 17, 6,
    'Zakho Road, Duhok', 'طريق زاخو، دهوك', 'ڕێگای زاخۆ، دهۆک', 36.8712, 42.9611, '+964 750 200 0601'],
  ['Erbil Traffic Directorate — Central', 'مديرية مرور أربيل المركزية', 'بەڕێوەبەرایەتی هاتوچۆی هەولێر ـ ناوەندی', 18, 4,
    '120m Street, Erbil', 'شارع المائة والعشرين، أربيل', 'شەقامی سەد و بیست مەتری، هەولێر', 36.2231, 44.0111, '+964 750 200 0402'],
  ['Anbar Residence Office', 'مكتب إقامة الأنبار', 'نووسینگەی نیشتەجێبوونی ئەنبار', 4, 9,
    'Al-Ramadi Centre, Anbar', 'مركز الرمادي، الأنبار', 'ناوەندی ڕەمادی، ئەنبار', 33.4201, 43.3077, '+964 780 200 0901'],
].map(([en, ar, ku, dirIdx, provIdx, aEn, aAr, aKu, lat, lon, phone], i) => ({
  id: pid('brn', i + 1),
  title_en: en, title_ar: ar, title_ku: ku,
  directorate: pid('dir', dirIdx), province: pid('prv', provIdx),
  address_en: aEn, address_ar: aAr, address_ku: aKu,
  gps_lat: lat, gps_lon: lon, phone, sort_order: i + 1, archived: false,
}));

export const tags = [
  ['passport', 'Passport', 'جواز السفر', 'پاسپۆرت'],
  ['national-id', 'National ID', 'البطاقة الوطنية', 'ناسنامەی نیشتمانی'],
  ['nationality', 'Nationality', 'الجنسية', 'ڕەگەزنامە'],
  ['civil-status', 'Civil Status', 'الأحوال المدنية', 'بارودۆخی مەدەنی'],
  ['driving', 'Driving', 'القيادة', 'لێخوڕین'],
  ['vehicles', 'Vehicles', 'المركبات', 'ئۆتۆمبێل'],
  ['residency', 'Residency', 'الإقامة', 'نیشتەجێبوون'],
  ['education', 'Education', 'التعليم', 'پەروەردە'],
  ['certificates', 'Certificates', 'الشهادات', 'بڕوانامەکان'],
  ['scholarships', 'Scholarships', 'البعثات الدراسية', 'بەخشینی خوێندن'],
  ['business', 'Business', 'الأعمال', 'بازرگانی'],
  ['taxes', 'Taxes', 'الضرائب', 'باج'],
  ['customs', 'Customs', 'الكمارك', 'گومرگ'],
  ['property', 'Property', 'العقارات', 'خانووبەرە'],
  ['family', 'Family', 'الأسرة', 'خێزان'],
  ['health', 'Health', 'الصحة', 'تەندروستی'],
  ['social-welfare', 'Social Welfare', 'الرعاية الاجتماعية', 'چاودێری کۆمەڵایەتی'],
  ['pensions', 'Pensions', 'التقاعد', 'خانەنشینی'],
  ['travel', 'Travel', 'السفر', 'گەشتکردن'],
  ['courts', 'Courts', 'المحاكم', 'دادگاکان'],
].map(([slug, en, ar, ku], i) => ({
  id: pid('tag', i + 1), slug, name_en: en, name_ar: ar, name_ku: ku,
}));

export const tagIdBySlug = Object.fromEntries(tags.map((t) => [t.slug, t.id]));
